language: node_js
node_js:
  - '8'
cache:
  directories:
  - node_modules
sudo: false
env:
  global:
  - NODE_ENV="CI"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn -v
  - npm i -g npm
  - cd js  
script:
  - yarn install
  - yarn build